// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNfNAFB__zLFonl-J3OiqPDvHtcEUh0Q',
    appId: '1:186554911522:web:3b8f6c3020a1d4ad2db37b',
    messagingSenderId: '186554911522',
    projectId: 'vaulted-bus-331021',
    authDomain: 'vaulted-bus-331021.firebaseapp.com',
    storageBucket: 'vaulted-bus-331021.appspot.com',
    measurementId: 'G-JM63NHHYP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBhIck4_vbOFJNM0HvdMag1Oh714PJq5w',
    appId: '1:186554911522:android:844f03352c7c04a92db37b',
    messagingSenderId: '186554911522',
    projectId: 'vaulted-bus-331021',
    storageBucket: 'vaulted-bus-331021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJKfx-jQXO7qOccPSyYQBug8zmCNAAtU',
    appId: '1:186554911522:ios:e84618b19d346a0b2db37b',
    messagingSenderId: '186554911522',
    projectId: 'vaulted-bus-331021',
    storageBucket: 'vaulted-bus-331021.appspot.com',
    androidClientId: '186554911522-8ca40fe1bgidmvblt2mge4hde5k0koq6.apps.googleusercontent.com',
    iosClientId: '186554911522-e4ud2g50evloec7ebmqj1id201ggio5m.apps.googleusercontent.com',
    iosBundleId: 'ios',
  );
}
